#- name: 01.1 Download file with custom HTTP headers
#  ansible.builtin.get_url:
#    url: "{{ archive_url }}"
#    dest: "{{ dest_archive_path }}"
#    headers:
#      PRIVATE-TOKEN: "{{ cred_config[gitlab_token[0]]['data'][gitlab_token[1]] }}"

#- name: 01.2 Create directory for cloud-passport
#  ansible.builtin.file:
#    path: "{{ passport_path }}"
#    state: directory


- name: 01.5 Get secret key for sensitive data
  uri:
    url: "{{ gitlab_vars_api }}/{{ secret_key_var_name }}"
    validate_certs: no
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ cred_config[gitlab_token[0]]['data'][gitlab_token[1]] }}"
    status_code: 200, 404
  register: secret_var_result

- name: 01.6 Set secret_key
  set_fact:
    discovery_secret_key: "{{ secret_var_result.json.value }}"

- name: 01.7 decrypt {{ discovery_sensitive_file }} with discovery tool secret-key
  crypt:
    crypt_type: "decrypt"
    secret_key: "{{ discovery_secret_key }}"
    source_file: "{{ discovery_sensitive_file }}"
    in_place: true
    crypt_backend: Fernet
  no_log: true

- name: 01.8 Add headers to cloud_passport files
  block:
    - name: Find cloud_passport files
      find:
        path: "{{ discovery_cloud_dir }}/cloud-passport/"
        file_type: file
      register: cloud_passport_files

    - name: Add headers to files
      add_header_to_yaml:
        path: "{{ item.path }}"
        text: "{{ header_text }}"
      with_items:
        - "{{ cloud_passport_files.files }}"
      no_log: true

- name: 01.9 Re-encrypt credential-cp file
  block:
    - name: encrypt {{ discovery_sensitive_file }} with instance secret-key
      crypt:
        crypt_type: "encrypt"
        source_file: "{{ discovery_sensitive_file }}"
        minimize_diff: true
        old_encrypted_file: "{{ old_discovery_sensitive_file }}"
        in_place: true

    - name: remove old_discovery_sensitive_file
      ansible.builtin.file:
        path: "{{ old_discovery_sensitive_file }}"
        state: absent
