service-activator-integration-cred: # shared credentials: prod-integration-creds
  type: usernamePassword
  data:
    username: "user-placeholder-123"
    password: "pass-placeholder-123"
tibco-integration-cred: # shared credentials: prod-integration-creds
  type: usernamePassword
  data:
    username: "user-placeholder-123"
    password: "pass-placeholder-123"
